### ISSUE TITLE
Reordering Toolbox with `KeypointSlider` errors out

### ISSUE THREAD

**Issue by joshua-dean** [SenteraLLC/ulabel#104]
Toolbox reordering is functional unless the `KeypointSlider` (item 6) is used, which causes an error as it has required constructor arguments. 
Good behavior would be omitting toolbox items that failed to construct, as well as having the parameters in `configuration.ts` be defaults in the actual `ToolboxItem` class.

**Comment by csolbs24** [comment]
Fixed in commit 865f662 on lines 937-951

**Comment by csolbs24** [comment]
Fixed in commit https://github.com/SenteraLLC/ulabel/commit/865f662c7b31affba94b6d24bdb7b9d059149e08 on lines 937-951
