### ISSUE TITLE
Can't use in vite + vue3

### ISSUE THREAD

**Issue by chenyuyu118** [SenteraLLC/ulabel#123]
Could not resolve "../build/annotation"

    node_modules/.store/ulabel@0.6.5/node_modules/ulabel/src/index.js:5:33:
      5 │ import { ULabelAnnotation } from '../build/annotation';
        ╵                                  ~~~~~~~~~~~~~~~~~~~~~

X [ERROR] Could not resolve "../build/subtask"

    node_modules/.store/ulabel@0.6.5/node_modules/ulabel/src/index.js:6:30:
      6 │ import { ULabelSubtask } from '../build/subtask';
        ╵                               ~~~~~~~~~~~~~~~~~~

X [ERROR] Could not resolve "../build/geometric_utils"

    node_modules/.store/ulabel@0.6.5/node_modules/ulabel/src/index.js:7:31:
      7 │ import { GeometricUtils } from '../build/geometric_utils';
        ╵                                ~~~~~~~~~~~~~~~~~~~~~~~~~~

X [ERROR] Could not resolve "../build/annotation_operators"

    node_modules/.store/ulabel@0.6.5/node_modules/ulabel/src/index.js:8:42:
      8 │ import { get_annotation_confidence } from '../build/annotation_operators';
        ╵                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

X [ERROR] Could not resolve "../build/drawing_utilities"

    node_modules/.store/ulabel@0.6.5/node_modules/ulabel/src/index.js:9:31:
      9 │ import { apply_gradient } from '../build/drawing_utilities'
        ╵                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

X [ERROR] Could not resolve "../build/configuration"

    node_modules/.store/ulabel@0.6.5/node_modules/ulabel/src/index.js:10:50:
      10 │ import { Configuration, AllowedToolboxItem } from '../build/configuration';
         ╵                                                   ~~~~~~~~~~~~~~~~~~~~~~~~

X [ERROR] Could not resolve "../build/html_builder"

    node_modules/.store/ulabel@0.6.5/node_modules/ulabel/src/index.js:11:28:
      11 │ import { HTMLBuilder } from '../build/html_builder';
         ╵                             ~~~~~~~~~~~~~~~~~~~~~~~

dist-electron/main.js  571.00 kB │ gzip: 169.08 kB
built in 33165ms.

X [ERROR] Could not resolve "../build/annotation"

    node_modules/.store/ulabel@0.6.5/node_modules/ulabel/src/index.js:5:33:
      5 │ import { ULabelAnnotation } from '../build/annotation';
        ╵                                  ~~~~~~~~~~~~~~~~~~~~~

X [ERROR] Could not resolve "../build/subtask"

    node_modules/.store/ulabel@0.6.5/node_modules/ulabel/src/index.js:6:30:
      6 │ import { ULabelSubtask } from '../build/subtask';
        ╵                               ~~~~~~~~~~~~~~~~~~

X [ERROR] Could not resolve "../build/geometric_utils"

    node_modules/.store/ulabel@0.6.5/node_modules/ulabel/src/index.js:7:31:
      7 │ import { GeometricUtils } from '../build/geometric_utils';
        ╵                                ~~~~~~~~~~~~~~~~~~~~~~~~~~

X [ERROR] Could not resolve "../build/annotation_operators"

    node_modules/.store/ulabel@0.6.5/node_modules/ulabel/src/index.js:8:42:
      8 │ import { get_annotation_confidence } from '../build/annotation_operators';
        ╵                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

X [ERROR] Could not resolve "../build/drawing_utilities"

    node_modules/.store/ulabel@0.6.5/node_modules/ulabel/src/index.js:9:31:
      9 │ import { apply_gradient } from '../build/drawing_utilities'
        ╵                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

X [ERROR] Could not resolve "../build/configuration"

    node_modules/.store/ulabel@0.6.5/node_modules/ulabel/src/index.js:10:50:
      10 │ import { Configuration, AllowedToolboxItem } from '../build/configuration';
         ╵                                                   ~~~~~~~~~~~~~~~~~~~~~~~~

X [ERROR] Could not resolve "../build/html_builder"

**Comment by TrevorBurgoyne** [comment]
@chenyuyu118 run `npm install ulabel` and update to version `0.6.12` and this should be resolved
