### ISSUE TITLE
Dialogs are not always visible

### ISSUE THREAD

**Issue by csolbs24** [SenteraLLC/ulabel#148]
Sometimes hovering over annotations does not cause dialogs to appear. This can be seen in demo/resume-from. If you hover over the polygon, you'll see that it works as expected. If you hover over the three keypoints on the left side of the screen, you'll see that no dialogs show up.

**Comment by TrevorBurgoyne** [comment]
The issue with those keypoints not showing is actually because they use the deprecated `line_width` argument instead of `line_size`. If you switch to `line_size` the dialogs will still work.

**Comment by csolbs24** [comment]
Closed by #149
