### ISSUE TITLE
Clean up branches

### ISSUE THREAD

**Issue by joshua-dean** [SenteraLLC/ulabel#173]
There's a lot of stale branches, most of which I think are from features that didn't get very far, or PRs that didn't delete the branch on merge. I'm ignoring branches that have open PRs for obvious reasons.

I've made some logical groups of them, ignoring branches with open PRs for obvious reasons.
## Not deleted after a PR
- `typescript-refactor`: #101 
- `bugfix/classes`: #49 
- `tiling-support`: #44 
- `patch`: #43  

## Purely behind `main`
All of these are 0 commits ahead, so any logic they added is already merged 
- `fix/classification-order` 
- `old-typescript` 

## Have unmerged changes 
I left a brief summary of what the changes appear to be 
- `fix/electron-compatibility`: Removes some jQuery selectors in favor of `document.` 
- `reorder-toolbox`: Manually shuffles toolbox order and tweaks old "demo" code
- `solve-jquery-error`: Tweaks a bunch of imports and exports

I don't think any of these are worth keeping. @TrevorBurgoyne @csolbs24 what's your input?

**Comment by TrevorBurgoyne** [comment]
those all look good to nuke from my end 🚀

**Comment by csolbs24** [comment]
Nuke em'

**Comment by TrevorBurgoyne** [comment]
nuked
