### ISSUE TITLE
Delete Modes shoud use `mark_deprecated`

### ISSUE THREAD

**Issue by TrevorBurgoyne** [SenteraLLC/ulabel#193]
Currently delete modes (that call `delete_annotations_in_polygon`) explicitly set `"deprecated" = true` for each annotation they are deleting. They should instead use `mark_deprecated` to be consistent with other usage. I have noticed that deleting points with a delete bbox for example will unexpectedly be undone by adjusting a slider bar, bc the `deprecated_by` field for the points was not correctly set by `mark_deprecated`

**Comment by joshua-dean** [comment]
Is it safe to assume that all of the existing delete mode cases are human-triggered deprecations? Can we foresee any case an automated method would be calling delete modes? 

We might want to add a note in the documentation about deprecation logic, so if it every comes up we can address it appropriately.
