### ISSUE TITLE
Integrating with react

### ISSUE THREAD

**Issue by salahCoone** [SenteraLLC/ulabel#51]
What is the correct way to integrate the package with react ?

**Comment by joshua-dean** [comment]
There is a ulabel npm package that can be imported into the project and then loaded as normal. It can also be loaded from a script tag refrencing that repo.
I've integrated this in vue projects (which should be somewhat similar) so if there's any specific setbacks I can take a look.

**Comment by Karthik-code1010** [comment]
How to integrate with angular

**Comment by salahCoone** [comment]
@joshua-dean thanks, I will share with you the problem I am facing. I'll grateful if you can help

**Comment by joshua-dean** [comment]
Check out [ulabel-react-demo](https://github.com/joshua-dean/ulabel-react-demo/) to see a bare-bones react project integrating ULabel.
